name: ai-assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - openai
  - pydub
  - streamlit
  - spyder-kernels=3.0
  - pip:
    - ollama
    - dotenv
    - google.generativeai
    - gradio